base_csv: data/merged/full_merged.csv
out_csv: data/merged/full_merged_with_fundamentals.csv
slim_csv: data/merged/full_merged_slim.csv
cols_txt: data/merged/fundamental_columns.txt
report_dir: data/merged/fuse_audit
validate: true
dataset_type: combined
no_nan_policy:
  enabled: false
  scope: onchain
  method: intersect
  columns: []
max_missing_ratio: 0.01
include_symbol:
  funding_oi: true
  funding_vol: false
  oi: true
  ls_global: true
  ls_top_acc: true
  ls_top_pos: true
  basis: true
  whale: true
  taker: true
  cgdi: true
  cdri: true
  borrow_interest: true
extra_field:
  name: baseline
  append_to_filename: none
  group_to_folder: true
  folder_mode: name
  folder_root: data/merged/expert_group
post_convert: &id001
  pkl: true
  parquet: false
  periods:
  - 1h
  - 4h
  - 1d
experts_map:
  Alpha-Dir-TFT_base:
    dataset_type: fundamentals_only
    max_missing_ratio: 0.01
    no_nan_policy:
      enabled: false
    include_symbol:
      funding_oi: true
      funding_vol: false
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global: {}
    extra_field:
      name: Alpha-Dir-TFT
      value: base
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  Alpha-Dir-TFT_rich:
    dataset_type: combined
    max_missing_ratio: null
    no_nan_policy:
      enabled: true
      scope: onchain
      method: intersect
    include_symbol:
      funding_oi: true
      funding_vol: true
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global:
      premium: true
      altcoin: true
      reserve: true
      correlation: true
      ahr999: true
      active_addresses: true
      new_addresses: true
      nupl: true
      sth_sopr: true
      lth_sopr: true
      sth_realized_price: true
      lth_realized_price: true
      lth_supply: true
      sth_supply: true
      macro_oscillator: true
      rhodl: true
      dominance: true
      m2_global: true
      m2_us: true
      stablecoin_mcap: true
      bubble_index: true
      rainbow_chart: true
      pi_cycle: true
      golden_ratio: true
      puell_multiple: true
      stock_flow: true
      etf_btc: true
      etf_eth: true
    extra_field:
      name: Alpha-Dir-TFT
      value: rich
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  Alpha-Ret-TFT_base:
    dataset_type: fundamentals_only
    max_missing_ratio: 0.01
    no_nan_policy:
      enabled: false
    include_symbol:
      funding_oi: true
      funding_vol: false
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global: {}
    extra_field:
      name: Alpha-Ret-TFT
      value: base
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  Alpha-Ret-TFT_rich:
    dataset_type: combined
    max_missing_ratio: null
    no_nan_policy:
      enabled: true
      scope: onchain
      method: intersect
    include_symbol:
      funding_oi: true
      funding_vol: true
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global:
      premium: true
      altcoin: true
      reserve: true
      correlation: true
      ahr999: true
      active_addresses: true
      new_addresses: true
      nupl: true
      sth_sopr: true
      lth_sopr: true
      sth_realized_price: true
      lth_realized_price: true
      lth_supply: true
      sth_supply: true
      macro_oscillator: true
      rhodl: true
      dominance: true
      m2_global: true
      m2_us: true
      stablecoin_mcap: true
      bubble_index: true
      rainbow_chart: true
      pi_cycle: true
      golden_ratio: true
      puell_multiple: true
      stock_flow: true
      etf_btc: true
      etf_eth: true
    extra_field:
      name: Alpha-Ret-TFT
      value: rich
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  Factor-Bridge-TFT_base:
    dataset_type: fundamentals_only
    max_missing_ratio: 0.01
    no_nan_policy:
      enabled: false
    include_symbol:
      funding_oi: true
      funding_vol: false
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global: {}
    extra_field:
      name: Factor-Bridge-TFT
      value: base
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  Factor-Bridge-TFT_rich:
    dataset_type: combined
    max_missing_ratio: null
    no_nan_policy:
      enabled: true
      scope: onchain
      method: intersect
    include_symbol:
      funding_oi: true
      funding_vol: true
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global:
      premium: true
      altcoin: true
      reserve: true
      correlation: true
      ahr999: true
      active_addresses: true
      new_addresses: true
      nupl: true
      sth_sopr: true
      lth_sopr: true
      sth_realized_price: true
      lth_realized_price: true
      lth_supply: true
      sth_supply: true
      macro_oscillator: true
      rhodl: true
      dominance: true
      m2_global: true
      m2_us: true
      stablecoin_mcap: true
      bubble_index: true
      rainbow_chart: true
      pi_cycle: true
      golden_ratio: true
      puell_multiple: true
      stock_flow: true
      etf_btc: true
      etf_eth: true
    extra_field:
      name: Factor-Bridge-TFT
      value: rich
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  KeyLevel-Breakout-TFT_base:
    dataset_type: fundamentals_only
    max_missing_ratio: 0.01
    no_nan_policy:
      enabled: false
    include_symbol:
      funding_oi: true
      funding_vol: false
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global: {}
    extra_field:
      name: KeyLevel-Breakout-TFT
      value: base
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  KeyLevel-Breakout-TFT_rich:
    dataset_type: combined
    max_missing_ratio: null
    no_nan_policy:
      enabled: true
      scope: onchain
      method: intersect
    include_symbol:
      funding_oi: true
      funding_vol: true
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global:
      premium: true
      altcoin: true
      reserve: true
      correlation: true
      ahr999: true
      active_addresses: true
      new_addresses: true
      nupl: true
      sth_sopr: true
      lth_sopr: true
      sth_realized_price: true
      lth_realized_price: true
      lth_supply: true
      sth_supply: true
      macro_oscillator: true
      rhodl: true
      dominance: true
      m2_global: true
      m2_us: true
      stablecoin_mcap: true
      bubble_index: true
      rainbow_chart: true
      pi_cycle: true
      golden_ratio: true
      puell_multiple: true
      stock_flow: true
      etf_btc: true
      etf_eth: true
    extra_field:
      name: KeyLevel-Breakout-TFT
      value: rich
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  MicroStruct-Deriv-TFT_base:
    dataset_type: fundamentals_only
    max_missing_ratio: 0.01
    no_nan_policy:
      enabled: false
    include_symbol:
      funding_oi: true
      funding_vol: false
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global: {}
    extra_field:
      name: MicroStruct-Deriv-TFT
      value: base
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  MicroStruct-Deriv-TFT_rich:
    dataset_type: combined
    max_missing_ratio: null
    no_nan_policy:
      enabled: true
      scope: onchain
      method: intersect
    include_symbol:
      funding_oi: true
      funding_vol: true
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global:
      premium: true
      altcoin: true
      reserve: true
      correlation: true
      ahr999: true
      active_addresses: true
      new_addresses: true
      nupl: true
      sth_sopr: true
      lth_sopr: true
      sth_realized_price: true
      lth_realized_price: true
      lth_supply: true
      sth_supply: true
      macro_oscillator: true
      rhodl: true
      dominance: true
      m2_global: true
      m2_us: true
      stablecoin_mcap: true
      bubble_index: true
      rainbow_chart: true
      pi_cycle: true
      golden_ratio: true
      puell_multiple: true
      stock_flow: true
      etf_btc: true
      etf_eth: true
    extra_field:
      name: MicroStruct-Deriv-TFT
      value: rich
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  OnChain-ETF-TFT_base:
    dataset_type: fundamentals_only
    max_missing_ratio: 0.01
    no_nan_policy:
      enabled: false
    include_symbol:
      funding_oi: true
      funding_vol: false
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global: {}
    extra_field:
      name: OnChain-ETF-TFT
      value: base
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  OnChain-ETF-TFT_rich:
    dataset_type: combined
    max_missing_ratio: null
    no_nan_policy:
      enabled: true
      scope: onchain
      method: intersect
    include_symbol:
      funding_oi: true
      funding_vol: true
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global:
      premium: true
      altcoin: true
      reserve: true
      correlation: true
      ahr999: true
      active_addresses: true
      new_addresses: true
      nupl: true
      sth_sopr: true
      lth_sopr: true
      sth_realized_price: true
      lth_realized_price: true
      lth_supply: true
      sth_supply: true
      macro_oscillator: true
      rhodl: true
      dominance: true
      m2_global: true
      m2_us: true
      stablecoin_mcap: true
      bubble_index: true
      rainbow_chart: true
      pi_cycle: true
      golden_ratio: true
      puell_multiple: true
      stock_flow: true
      etf_btc: true
      etf_eth: true
    extra_field:
      name: OnChain-ETF-TFT
      value: rich
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  RelativeStrength-Spread-TFT_base:
    dataset_type: fundamentals_only
    max_missing_ratio: 0.01
    no_nan_policy:
      enabled: false
    include_symbol:
      funding_oi: true
      funding_vol: false
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global: {}
    extra_field:
      name: RelativeStrength-Spread-TFT
      value: base
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  RelativeStrength-Spread-TFT_rich:
    dataset_type: combined
    max_missing_ratio: null
    no_nan_policy:
      enabled: true
      scope: onchain
      method: intersect
    include_symbol:
      funding_oi: true
      funding_vol: true
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global:
      premium: true
      altcoin: true
      reserve: true
      correlation: true
      ahr999: true
      active_addresses: true
      new_addresses: true
      nupl: true
      sth_sopr: true
      lth_sopr: true
      sth_realized_price: true
      lth_realized_price: true
      lth_supply: true
      sth_supply: true
      macro_oscillator: true
      rhodl: true
      dominance: true
      m2_global: true
      m2_us: true
      stablecoin_mcap: true
      bubble_index: true
      rainbow_chart: true
      pi_cycle: true
      golden_ratio: true
      puell_multiple: true
      stock_flow: true
      etf_btc: true
      etf_eth: true
    extra_field:
      name: RelativeStrength-Spread-TFT
      value: rich
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  Risk-TFT_base:
    dataset_type: fundamentals_only
    max_missing_ratio: 0.01
    no_nan_policy:
      enabled: false
    include_symbol:
      funding_oi: true
      funding_vol: false
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global: {}
    extra_field:
      name: Risk-TFT
      value: base
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  Risk-TFT_rich:
    dataset_type: combined
    max_missing_ratio: null
    no_nan_policy:
      enabled: true
      scope: onchain
      method: intersect
    include_symbol:
      funding_oi: true
      funding_vol: true
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global:
      premium: true
      altcoin: true
      reserve: true
      correlation: true
      ahr999: true
      active_addresses: true
      new_addresses: true
      nupl: true
      sth_sopr: true
      lth_sopr: true
      sth_realized_price: true
      lth_realized_price: true
      lth_supply: true
      sth_supply: true
      macro_oscillator: true
      rhodl: true
      dominance: true
      m2_global: true
      m2_us: true
      stablecoin_mcap: true
      bubble_index: true
      rainbow_chart: true
      pi_cycle: true
      golden_ratio: true
      puell_multiple: true
      stock_flow: true
      etf_btc: true
      etf_eth: true
    extra_field:
      name: Risk-TFT
      value: rich
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  Regime-Gate_base:
    dataset_type: fundamentals_only
    max_missing_ratio: 0.01
    no_nan_policy:
      enabled: false
    include_symbol:
      funding_oi: true
      funding_vol: false
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global: {}
    extra_field:
      name: Regime-Gate
      value: base
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
  Regime-Gate_rich:
    dataset_type: combined
    max_missing_ratio: null
    no_nan_policy:
      enabled: true
      scope: onchain
      method: intersect
    include_symbol:
      funding_oi: true
      funding_vol: true
      oi: true
      ls_global: true
      ls_top_acc: true
      ls_top_pos: true
      basis: true
      whale: true
      taker: true
      cgdi: true
      cdri: true
      borrow_interest: true
    include_global:
      premium: true
      altcoin: true
      reserve: true
      correlation: true
      ahr999: true
      active_addresses: true
      new_addresses: true
      nupl: true
      sth_sopr: true
      lth_sopr: true
      sth_realized_price: true
      lth_realized_price: true
      lth_supply: true
      sth_supply: true
      macro_oscillator: true
      rhodl: true
      dominance: true
      m2_global: true
      m2_us: true
      stablecoin_mcap: true
      bubble_index: true
      rainbow_chart: true
      pi_cycle: true
      golden_ratio: true
      puell_multiple: true
      stock_flow: true
      etf_btc: true
      etf_eth: true
    extra_field:
      name: Regime-Gate
      value: rich
      append_to_filename: both
      group_to_folder: true
      folder_mode: both
    post_convert: *id001
