base_csv: data/merged/full_merged.csv
out_csv: data/merged/full_merged_with_fundamentals.csv
slim_csv: data/merged/full_merged_slim.csv
cols_txt: data/merged/fundamental_columns.txt
report_dir: data/merged/fuse_audit
validate: true
dataset_type: combined
no_nan_policy:
  enabled: false
  scope: onchain
  method: intersect
  columns: []
max_missing_ratio: 0.01
include_symbol:
  funding_oi: true
  funding_vol: false
  oi: true
  ls_global: true
  ls_top_acc: true
  ls_top_pos: true
  basis: true
  whale: true
  taker: true
  cgdi: false
  cdri: false
  borrow_interest: false
extra_field:
  name: baseline
  append_to_filename: none
  group_to_folder: true
  folder_mode: name
  folder_root: data/merged/expert_group
post_convert:
  pkl: true
  parquet: false
  periods:
  - 1h
  - 4h
  - 1d
experts_map:
  Alpha-Dir-TFT_base: configs/experts/Alpha-Dir-TFT/datasets/base.yaml
  Alpha-Dir-TFT_rich: configs/experts/Alpha-Dir-TFT/datasets/rich.yaml
  Alpha-Ret-TFT_base: configs/experts/Alpha-Ret-TFT/datasets/base.yaml
  Alpha-Ret-TFT_rich: configs/experts/Alpha-Ret-TFT/datasets/rich.yaml
  Factor-Bridge-TFT_base: configs/experts/Factor-Bridge-TFT/datasets/base.yaml
  Factor-Bridge-TFT_rich: configs/experts/Factor-Bridge-TFT/datasets/rich.yaml
  KeyLevel-Breakout-TFT_base: configs/experts/KeyLevel-Breakout-TFT/datasets/base.yaml
  KeyLevel-Breakout-TFT_rich: configs/experts/KeyLevel-Breakout-TFT/datasets/rich.yaml
  MicroStruct-Deriv-TFT_base: configs/experts/MicroStruct-Deriv-TFT/datasets/base.yaml
  MicroStruct-Deriv-TFT_rich: configs/experts/MicroStruct-Deriv-TFT/datasets/rich.yaml
  OnChain-ETF-TFT_base: configs/experts/OnChain-ETF-TFT/datasets/base.yaml
  OnChain-ETF-TFT_rich: configs/experts/OnChain-ETF-TFT/datasets/rich.yaml
  Regime-Gate_base: configs/experts/Regime-Gate/datasets/base.yaml
  Regime-Gate_rich: configs/experts/Regime-Gate/datasets/rich.yaml
  RelativeStrength-Spread-TFT_base: configs/experts/RelativeStrength-Spread-TFT/datasets/base.yaml
  RelativeStrength-Spread-TFT_rich: configs/experts/RelativeStrength-Spread-TFT/datasets/rich.yaml
  Risk-Prob-TFT_base: configs/experts/Risk-Prob-TFT/datasets/base.yaml
  Risk-Prob-TFT_rich: configs/experts/Risk-Prob-TFT/datasets/rich.yaml
  Risk-Reg-TFT_base: configs/experts/Risk-Reg-TFT/datasets/base.yaml
  Risk-Reg-TFT_rich: configs/experts/Risk-Reg-TFT/datasets/rich.yaml
