data_path: data/pkl_merged/full_merged_base.pkl
expert: Alpha-Dir-TFT
period: "4h"
modality_set: base

val_mode: days
val_days: 252

batch_size: 128
num_workers: 4
hidden_size: 128
lstm_layers: 1
attention_head_size: 2
dropout: 0.1
learning_rate: 1.0e-3
max_epochs: 40
precision: "16-mixed"
grad_clip: 0.2
accumulate: 1
early_stop_patience: 3
log_name: Alpha-Dir-TFT_4h_base


