data_path: data/merged/expert_group/Risk-Prob-TFT-base/full_merged_with_fundamentals_Risk-Prob-TFT-base.pkl
expert: Risk-Prob-TFT
modality_set: rich
val_mode: ratio
val_ratio: 0.2
val_days: 14
batch_size: 128
num_workers: 4
hidden_size: 64
lstm_layers: 1
attention_head_size: 2
dropout: 0.1
learning_rate: 0.003
max_epochs: 2
precision: 16-mixed
grad_clip: 0.2
accumulate: 1
early_stop_patience: 3
min_epochs: 3
monitor: val_loss
devices: 1
log_interval: 100
log_val_interval: 1
log_every_n_steps: 100
schema_version: schema_v1
data_version: data_unknown
expert_version: expert_unknown
train_window_id: window_unknown
enable_calibration: false
early_stop_min_delta: 0.0001
detailed_logging: false
log_on_step: false
max_encoder_length: 36
max_prediction_length: 1
add_relative_time_idx: true
add_target_scales: false
allow_missing_timesteps: true
static_categoricals:
- symbol
- period
static_reals: []
log_metrics_to_prog_bar: false
period: 1h
log_name: Risk-Prob-TFT_1h_rich
