data_path: data/merged/full_merged.csv
resume_ckpt: checkpoints/last.ckpt
warm_start_ckpt: checkpoints/best.ckpt


# 验证集划分方式
val_mode: ratio
val_days: 14     # 若 val_mode = "days"
val_ratio: 0.2   # 若 val_mode = "ratio"
batch_size: 128
num_workers: 1
hidden_size: 64
lstm_layers: 1
attention_head_size: 2
dropout: 0.1
learning_rate: 3.0e-3
max_epochs: 2
precision: "16-mixed"
grad_clip: 0.2
accumulate: 1
early_stop_patience: 3
log_name: gating_quick

loss_schedule:
  0: [6.0, 3.0, 4.0, 1.5, 3.5, 2.5, 1.5, 1.2, 1.2, 1.8, 1.3]
  5: [5.0, 3.0, 3.5, 1.5, 3.0, 2.0, 1.5, 1.0, 1.0, 1.5, 1.0]


#    python train_multi_tft.py --config configs/model_config.yaml   
#  python train_resume.py 



