default_expert: alpha_reg

experts:
  alpha_reg:
    model_type: tft
    targets:
      - target_logreturn
  alpha:
    model_type: tft
    targets:
      - target_binarytrend
      - target_pullback_prob
      - target_sideway_detect
      - target_drawdown_prob
  tech_clf:
    model_type: tft
    targets:
      - target_binarytrend
      - target_pullback_prob
      - target_sideway_detect
      - target_drawdown_prob

  tech_reg:
    model_type: tft
    targets:
      - target_logreturn
      - target_logsharpe_ratio
      - target_breakout_count
      - target_max_drawdown
      - target_trend_persistence

  # === Experts (new MoE taxonomy) ===
  Alpha-Dir-TFT:
    model_type: tft
    targets:
      - target_binarytrend
  Alpha-Ret-TFT:
    model_type: tft
    targets:
      - target_logreturn
  Risk-TFT:
    model_type: tft
    targets:
      - target_drawdown_prob
  MicroStruct-Deriv-TFT:
    model_type: tft
    targets:
      - target_binarytrend
  OnChain-ETF-TFT:
    model_type: tft
    targets:
      - target_binarytrend
  Regime-Gate:
    model_type: tft
    targets:
      - target_sideway_detect
  KeyLevel-Breakout-TFT:
    model_type: tft
    targets:
      - target_breakout_count
  RelativeStrength-Spread-TFT:
    model_type: tft
    targets:
      - target_logreturn
  Factor-Bridge-TFT:
    model_type: tft
    targets:
      - target_logsharpe_ratio
  Z-Combiner:
    model_type: combiner
    targets: []
