custom_weights:
  - 6.0   # target_binarytrend
  - 3.0   # target_logreturn
  - 4.0   # target_logsharpe_ratio
  - 1.5   # target_breakout_count
  - 3.5   # target_drawdown_prob
  - 2.5   # target_max_drawdown
  - 1.5   # target_pullback_prob
  - 1.2   # target_return_outlier_lower_10
  - 1.2   # target_return_outlier_upper_90
  - 1.8   # target_sideway_detect
  - 1.3   # target_trend_persistence
