dataset_type: fundamentals_only
max_missing_ratio: 0.01
feature_list_path: reports/feature_evidence/Factor-Bridge-TFT/base/selected_features.txt
no_nan_policy:
  enabled: false
include_symbol:
  funding_oi: false
  funding_vol: false
  oi: false
  ls_global: false
  ls_top_acc: false
  ls_top_pos: false
  basis: false
  whale: false
  taker: false
  cgdi: false
  cdri: false
  borrow_interest: false
include_global: {}
extra_field:
  name: Factor-Bridge-TFT
  value: base
  append_to_filename: both
  group_to_folder: true
  folder_mode: both
  folder_root: data/merged/expert_group
post_convert:
  pkl: true
  parquet: false
  periods:
  - 1h
  - 4h
  - 1d