data_path: data/pkl_merged/full_merged.pkl
expert: RelativeStrength-Spread-TFT
period: "4h"
modality_set: base

val_mode: ratio
val_ratio: 0.2
val_days: 14

batch_size: 128
num_workers: 4
hidden_size: 64
lstm_layers: 1
attention_head_size: 2
dropout: 0.1
learning_rate: 3.0e-3
max_epochs: 2
precision: "16-mixed"
grad_clip: 0.2
accumulate: 1
early_stop_patience: 3
log_name: RelativeStrength-Spread-TFT_4h_base

min_epochs: 3
monitor: val_loss
devices: 1
log_interval: 100
log_val_interval: 1
log_every_n_steps: 100
schema_version: schema_v1
data_version: data_unknown
expert_version: expert_unknown
train_window_id: window_unknown
enable_calibration: false
max_encoder_length: 36
max_prediction_length: 1
add_relative_time_idx: true
add_target_scales: false
allow_missing_timesteps: true
static_categoricals:
  - symbol
  - period
static_reals: []
